package org.apache.jsp.layouts.generic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.jboss.portal.server.PortalConstants;
import java.util.ResourceBundle;

public final class maximized_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/WEB-INF/theme/portal-layout.tld");
    _jspx_dependants.add("/layouts/common/modal_head.jsp");
    _jspx_dependants.add("/layouts/common/modal_body.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
 ResourceBundle rb = ResourceBundle.getBundle("Resource", request.getLocale()); 
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n");
      out.write("\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("    <title>");
      //  p:title
      org.jboss.portal.theme.tag.TitleTagHandler _jspx_th_p_005ftitle_005f0 = new org.jboss.portal.theme.tag.TitleTagHandler();
      org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005ftitle_005f0);
      _jspx_th_p_005ftitle_005f0.setJspContext(_jspx_page_context);
      // /layouts/generic/maximized.jsp(9,11) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_p_005ftitle_005f0.setDefault( PortalConstants.VERSION.toString() );
      _jspx_th_p_005ftitle_005f0.doTag();
      org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005ftitle_005f0);
      out.write("</title>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html;\"/>\n");
      out.write("    <!-- to correct the unsightly Flash of Unstyled Content. -->\n");
      out.write("    <script type=\"text/javascript\"></script>\n");
      out.write("    <!-- use the renewal theme if nothing else was defined for the portal or the page -->\n");
      out.write("    ");
      if (_jspx_meth_p_005ftheme_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    <!-- inject header content that was generated by the portlets on the requested page -->\n");
      out.write("    ");
      if (_jspx_meth_p_005fheaderContent_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("    ");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/modal.js\" type=\"text/javascript\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/modal.css\" type=\"text/css\" />");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"body\">\n");
      if (_jspx_meth_p_005fregion_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write("   <div id=\"login-modal\" style=\"display:none\">\n");
      out.write("      <div id=\"login-modal-msg\" style=\"display:none;width:957px;height:387px\">\n");
      out.write("      <iframe src=\"\" frameborder=\"0\" width=\"957\" height=\"387\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" name=\"login-content\" class=\"login-content\" id=\"loginIframe\"></iframe>\n");
      out.write("      </div>\n");
      out.write("   </div>\n");
      out.write("\n");
      out.write("<div id=\"portal-container\">\n");
      out.write("    <div id=\"sizer\">\n");
      out.write("        <div id=\"expander\">\n");
      out.write("            <div id=\"logoName\"></div>\n");
      out.write("            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"header-container\">\n");
      out.write("                <tr>\n");
      out.write("                    <td align=\"center\" valign=\"top\" id=\"header\">\n");
      out.write("                        ");
      if (_jspx_meth_p_005fregion_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("                        ");
      if (_jspx_meth_p_005fregion_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                        <div id=\"spacer\"></div>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <div id=\"content-container\">\n");
      out.write("                <!-- Note: this construct assumes that the 'maximizedRegion' layout strategy was chosen for the layout, page or portal -->\n");
      out.write("                <!-- the 'maximizedRegion' strategy assigns the maximized portlet to the 'maximized' region -->\n");
      out.write("                ");
      if (_jspx_meth_p_005fregion_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                <hr class=\"cleaner\"/>\n");
      out.write("\n");
      out.write("                <div id=\"footer-container\" class=\"portal-copyright\">");
      out.print( rb.getString("POWERED_BY") );
      out.write("\n");
      out.write("                    <a class=\"portal-copyright\" href=\"http://www.jboss.com/products/jbossportal\">JBoss Portal</a><br>\n");
      out.write("                    <span id=\"ThemeBy\"></span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      if (_jspx_meth_p_005fregion_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_p_005ftheme_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:theme
    org.jboss.portal.theme.tag.ThemeTagHandler _jspx_th_p_005ftheme_005f0 = new org.jboss.portal.theme.tag.ThemeTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005ftheme_005f0);
    _jspx_th_p_005ftheme_005f0.setJspContext(_jspx_page_context);
    // /layouts/generic/maximized.jsp(14,4) name = themeName type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005ftheme_005f0.setThemeName("renewal");
    _jspx_th_p_005ftheme_005f0.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005ftheme_005f0);
    return false;
  }

  private boolean _jspx_meth_p_005fheaderContent_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:headerContent
    org.jboss.portal.theme.tag.HeaderContentTagHandler _jspx_th_p_005fheaderContent_005f0 = new org.jboss.portal.theme.tag.HeaderContentTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005fheaderContent_005f0);
    _jspx_th_p_005fheaderContent_005f0.setJspContext(_jspx_page_context);
    _jspx_th_p_005fheaderContent_005f0.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005fheaderContent_005f0);
    return false;
  }

  private boolean _jspx_meth_p_005fregion_005f0(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:region
    org.jboss.portal.theme.tag.RegionTagHandler _jspx_th_p_005fregion_005f0 = new org.jboss.portal.theme.tag.RegionTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f0);
    _jspx_th_p_005fregion_005f0.setJspContext(_jspx_page_context);
    // /layouts/generic/maximized.jsp(21,0) name = regionName type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f0.setRegionName("AJAXScripts");
    // /layouts/generic/maximized.jsp(21,0) name = regionID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f0.setRegionID("AJAXScripts");
    _jspx_th_p_005fregion_005f0.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f0);
    return false;
  }

  private boolean _jspx_meth_p_005fregion_005f1(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:region
    org.jboss.portal.theme.tag.RegionTagHandler _jspx_th_p_005fregion_005f1 = new org.jboss.portal.theme.tag.RegionTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f1);
    _jspx_th_p_005fregion_005f1.setJspContext(_jspx_page_context);
    // /layouts/generic/maximized.jsp(30,24) name = regionName type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f1.setRegionName("dashboardnav");
    // /layouts/generic/maximized.jsp(30,24) name = regionID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f1.setRegionID("dashboardnav");
    _jspx_th_p_005fregion_005f1.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f1);
    return false;
  }

  private boolean _jspx_meth_p_005fregion_005f2(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:region
    org.jboss.portal.theme.tag.RegionTagHandler _jspx_th_p_005fregion_005f2 = new org.jboss.portal.theme.tag.RegionTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f2);
    _jspx_th_p_005fregion_005f2.setJspContext(_jspx_page_context);
    // /layouts/generic/maximized.jsp(32,24) name = regionName type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f2.setRegionName("navigation");
    // /layouts/generic/maximized.jsp(32,24) name = regionID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f2.setRegionID("navigation");
    _jspx_th_p_005fregion_005f2.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f2);
    return false;
  }

  private boolean _jspx_meth_p_005fregion_005f3(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:region
    org.jboss.portal.theme.tag.RegionTagHandler _jspx_th_p_005fregion_005f3 = new org.jboss.portal.theme.tag.RegionTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f3);
    _jspx_th_p_005fregion_005f3.setJspContext(_jspx_page_context);
    // /layouts/generic/maximized.jsp(40,16) name = regionName type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f3.setRegionName("maximized");
    // /layouts/generic/maximized.jsp(40,16) name = regionID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f3.setRegionID("regionMaximized");
    _jspx_th_p_005fregion_005f3.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f3);
    return false;
  }

  private boolean _jspx_meth_p_005fregion_005f4(PageContext _jspx_page_context)
          throws Throwable {
    PageContext pageContext = _jspx_page_context;
    JspWriter out = _jspx_page_context.getOut();
    //  p:region
    org.jboss.portal.theme.tag.RegionTagHandler _jspx_th_p_005fregion_005f4 = new org.jboss.portal.theme.tag.RegionTagHandler();
    org.apache.jasper.runtime.AnnotationHelper.postConstruct(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f4);
    _jspx_th_p_005fregion_005f4.setJspContext(_jspx_page_context);
    // /layouts/generic/maximized.jsp(52,0) name = regionName type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f4.setRegionName("AJAXFooter");
    // /layouts/generic/maximized.jsp(52,0) name = regionID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_p_005fregion_005f4.setRegionID("AJAXFooter");
    _jspx_th_p_005fregion_005f4.doTag();
    org.apache.jasper.runtime.AnnotationHelper.preDestroy(_jsp_annotationprocessor, _jspx_th_p_005fregion_005f4);
    return false;
  }
}
